### ISSUE TITLE
有两个问题反馈

### ISSUE THREAD

**Issue by omiswang** [qlwz/esp_zinguo#3]
你好，大神，看到你还在改代码，反馈一下两个问题：
1.取暖经常会莫名奇妙的自己就打开了，这个很困扰，费电啊。。。。
2.实验了一下，发现如果WIFI联网的，按键会非常不灵敏，如果把WIFI 断掉，发现按键基本就正常 了，感觉时网络消息处理哪里占时过长影响了按键消息的处理。

如果能解决上述两个问题， 这个固件就完美了。
希望您能看到并回复。

多谢了~

**Comment by kylinfedora** [comment]
昨天发现取暖莫名奇妙的自动打开，然后还死机了，关闭总闸后好了，希望大神看看！

**Comment by qlwz** [comment]
使用时关闭web页面
