### ISSUE TITLE
编译失败了

### ISSUE THREAD

**Issue by kylinfedora** [qlwz/esp_zinguo#4]
你好！按照你的文档编译了下，编译没有通过，麻烦你看下
Archiving .pio\build\zinguo\lib58a\libTicker.a
Compiling .pio\build\zinguo\lib670\ESP8266WiFi\ESP8266WiFiGeneric.cpp.o
src\Zinguo.cpp: In member function 'virtual void Zinguo::loop()':
src\Zinguo.cpp:55:21: error: 'Log' has not been declared
                     Log::Info(PSTR("TouchKey: 0x%0X"), key);
                     ^
src\Zinguo.cpp:72:13: error: 'WifiMgr' has not been declared
             WifiMgr::setupWifiManager(false);
             ^
src\Zinguo.cpp:113:13: error: 'Log' has not been declared
             Log::Info(PSTR("Ventilation Timeout %d %d"), ventilationTime, perSecond);
             ^
src\Zinguo.cpp:120:13: error: 'Log' has not been declared
             Log::Info(PSTR("Warm Timeout %d %d"), warmTime, perSecond);
             ^
src\Zinguo.cpp: In member function 'virtual void Zinguo::resetConfig()':
src\Zinguo.cpp:170:5: error: 'Log' has not been declared
     Log::Info(PSTR("moduleResetConfig . . . OK"));
     ^
Archiving .pio\build\zinguo\lib3dd\libPubSubClient.a
Compiling .pio\build\zinguo\lib670\ESP8266WiFi\ESP8266WiFiMulti.cpp.o
*** [.pio\build\zinguo\src\Zinguo.cpp.o] Error 1
=========================================================== [FAILED] Took 40.81 seconds ===========================================================

Environment    Status    Duration
-------------  --------  ------------
zinguo         FAILED    00:00:40.815
====================================================== 1 failed, 0 succeeded in 00:00:40.815 ====================================================== 
终端进程“C:\Users\kylin\.platformio\penv\Scripts\platformio.exe 'run'”已终止，退出代码: 1。

**Comment by qlwz** [comment]
git pull一下 删除.pio文件夹重新编译
