### ISSUE TITLE
到底是8285还是8266？支持直接homekit吗？

### ISSUE THREAD

**Issue by Primovist** [qlwz/esp_zinguo#6]
看了一下代码，发现很多地方还是8266，还有最近的更新写了支持直接homekit，密码全是1，运行正常吗？买的一个8285在路上，手头有一个8266，我该用哪个开干？新编译的固件支持homekit吗？如果不支持，想支持homekit的话就需要自己编译了。

**Comment by Primovist** [comment]
编译了一下homekit版，不成功，提示找不到homekit.h，改成homekit/homekit.h后，提示几个参数未定义。我太难了😭

**Comment by Primovist** [comment]
src/main.cpp: In function 'void setup()':
src/main.cpp:22:18: error: 'homekit_init' was not declared in this scope
     homekit_init();
                  ^
src/main.cpp: In function 'void loop()':
src/main.cpp:29:18: error: 'homekit_loop' was not declared in this scope
     homekit_loop();
                  ^
Archiving .pio/build/zinguo-homekit/libf2e/libEEPROM.a
src/Zinguo.cpp: In member function 'virtual void Zinguo::httpAdd(ESP8266WebServer*)':
src/Zinguo.cpp:331:42: error: 'homekit_http' was not declared in this scope
     server->on(F("/homekit"), std::bind(&homekit_http, server));
                                          ^
src/Zinguo.cpp: In member function 'virtual void Zinguo::httpHtml(ESP8266WebServer*)':
src/Zinguo.cpp:469:24: error: 'homekit_html' was not declared in this scope
     homekit_html(server);
                        ^
*** [.pio/build/zinguo-homekit/src/main.cpp.o] Error 1
Indexing .pio/build/zinguo-homekit/libf2e/libEEPROM.a
*** [.pio/build/zinguo-homekit/src/Zinguo.cpp.o] Error 1

**Comment by qlwz** [comment]
8266和8285是同一个芯片， 峥果是否使用根据硬件图片判断

homekit代码不开源

**Comment by Primovist** [comment]
> 8266和8285是同一个芯片， 峥果是否使用根据硬件图片判断
> 
> 
> 
> homekit代码不开源

好的大佬，如果不能直接homekit我就不自己编译，用大佬编译好的了。谢谢！

**Comment by Primovist** [comment]
如果大佬有编译好的homekit版本，可以发一个给我吗😭
